apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
  labels:
    app: app-server
spec:
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
      - name: webapp
        image: gautadas/javamavenwebapp:v1.0.2
        ports:
        - containerPort: 8000
